<?php
/**
 * @var Klevu\FrontendJs\Block\Html\Head\JsApiKeys $block
 */
?>

<?php
$scriptString = <<<script
    klevu({$block->getJsApiKeysSerialized()});
script;

$script = $block->isDeferJs()
    ? <<<script
        window._klvReady = window._klvReady || [];
        window._klvReady.push(function() {
            {$scriptString}
        });

script
    : $scriptString;
?>

<script type="text/javascript" id="klevu_jsapikeys">
    <?= $script ?>
</script>
