<?php
/**
 * @var Klevu\FrontendJs\Block\Html\Head\JsApiKeys $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php
$scriptString = <<<script
    klevu({$block->getJsApiKeysSerialized()});
script;

$script = $block->isDeferJs()
    ? <<<script
        window._klvReady = window._klvReady || [];
        window._klvReady.push(function() {
            {$scriptString}
        });

script
    : $scriptString;
?>
<?= $secureRenderer->renderTag(
    'script',
    [
        'type' => 'text/javascript',
        'id' => 'klevu_jsapikeys',
    ],
    $script,
    false
) ?>
