<?php
/**
 * @var Klevu\FrontendJs\Block\Html\Head\JsDeferredPowerUp $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php
$scriptString = "
    klevu({$block->getJsDeferredPowerUpSerialized()});
";

$script = $block->isDeferJs()
    ? "
        window._klvReady = window._klvReady || [];
        window._klvReady.push(function() {
            {$scriptString}
        });"
    : $scriptString;
?>
<?= $secureRenderer->renderTag(
    'script',
    [
        'type' => 'text/javascript',
        'id' => 'klevu_jsdeferredpowerup',
    ],
    $script,
    false
) ?>
