<?php
/**
 * @var Klevu\FrontendJs\Block\Html\Head\JsIncludes $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$jsIncludesUrls = $block->getJsIncludesUrls();
?>

<?php foreach ($jsIncludesUrls as $jsIncludesUrl): ?>
    <?php
        $tagAttributes = [
            'type' => 'text/javascript',
            'src' => $block->escapeUrl($jsIncludesUrl),
        ];
        if ($block->isDeferJs()) {
            $tagAttributes['defer'] = 'defer';
        }
    ?>

    <?= $secureRenderer->renderTag(
        'script',
        $tagAttributes,
        null,
        true
    ) ?>
<?php endforeach; ?>
