<?php
/**
 * @var Klevu\FrontendJs\Block\Html\Head\JsInit $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$scriptString = <<<script

    klevu.interactive(function () {
        var options = {$block->getInteractiveOptionsSerialized()};
        {$block->getChildHtml('additional_before')}
        klevu(options);
        {$block->getChildHtml('additional_after')}
    });

script;
?>
<?= $secureRenderer->renderTag(
    'script',
    ['type' => 'text/javascript', 'id' => 'klevu_jsinteractive'],
    $scriptString,
    false
) ?>
