<?php
/**
 * @var Klevu\FrontendJs\Block\Html\Head\JsInit $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$scriptString = "
    klevu.interactive(function () {
        var options = {$block->getInteractiveOptionsSerialized()};
        {$block->getChildHtml('additional_before')}
        klevu(options);
        {$block->getChildHtml('additional_after')}
    });
";

$script = $block->isDeferJs()
    ? "
        window._klvReady = window._klvReady || [];
        window._klvReady.push(function() {
            klevu.support.hook([\"recs\"], function() {
                {$scriptString}
            });
        });"
    : $scriptString;
?>
<?= $secureRenderer->renderTag(
    'script',
    [
        'type' => 'text/javascript',
        'id' => 'klevu_jsinteractive',
    ],
    $script,
    false
) ?>
