<?php
/**
 * @var Klevu\FrontendJs\Block\Html\Head\JsIncludes $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$jsIncludesUrls = $block->getJsIncludesUrls();
?>

<?php foreach ($jsIncludesUrls as $jsIncludesUrl): ?>
<?= $secureRenderer->renderTag(
    'script',
    [
        'type' => 'text/javascript',
        'src' => $block->escapeUrl($jsIncludesUrl)
    ],
    null,
    true
) ?>

<?php endforeach; ?>
