<?php
/**
 * @var Klevu\FrontendJs\Block\Html\Head\JsModules $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */ ?>

<?php
$priceSuffixString = <<<script
    // Add Price Field Suffix for customer group and currency conversion
    // When javascript is deferred the calling code must use window._klvReady
    var klevu_addPriceSuffixToQueryControl = {
        name: 'addPriceSuffixToQuery',
        fire: function (data, scope) {
            var localStorage = JSON.parse(
                window.localStorage.getItem('{$block->getLocalStorageKey()}') || '{}'
            );
            var customerData = localStorage.{$block->getCustomerDataKey()} || {};
            if ("undefined" !== typeof customerData.customer_group_id) {
                klevu.search.modules.addPriceSuffixToQuery(data, scope, klevu_baseCurrencyCode, customerData.customer_group_id);
            }
        }
    };

script;
?>
<?php
$scriptString = <<<script
    (function (klevu) {
        klevu.extend(true, klevu.search.modules, {
            addPriceSuffixToQuery: function (data, scope, currencyCode, customerGroupId) {
                if (typeof data.request.current === "undefined") {
                    return false;
                }

                klevu.each(data.request.current.recordQueries, function (key, query) {
                    //code to fetch prices
                    klevu.setObjectPath(
                        data,
                        "localOverrides.query." + query.id + ".settings.priceFieldSuffix",
                        currencyCode + '-' + customerGroupId
                    );
                });
            },

            mageConvertPriceRecordCurrencyData: function (productRecords, currencyCode, currencyRates) {
                if (!productRecords) {
                    return;
                }
                klevu.each(productRecords, function (recordKey, productRecord) {
                    var fromRate = parseFloat(currencyRates[productRecord.currency] || 0);
                    var toRate = parseFloat(currencyRates[currencyCode] || 0);
                    if (!fromRate || !toRate) {
                        return;
                    }
                    var exchangeRate = toRate / fromRate;
                    if (klevu.isNumeric(klevu.getObjectPath(productRecord, "price"))) {
                        productRecord.price *= exchangeRate;
                    }
                    if (klevu.isNumeric(klevu.getObjectPath(productRecord, "salePrice"))) {
                        productRecord.salePrice *= exchangeRate;
                    }
                    if (klevu.isNumeric(klevu.getObjectPath(productRecord, "startPrice"))) {
                        productRecord.startPrice *= exchangeRate;
                    }

                    productRecord.currency = currencyCode;
                });
            }
        });
    })(klevu);

script;
?>
<?php
$script = $block->isDeferJs()
    ? <<<script
        window._klvReady = window._klvReady || [];
        window._klvReady.push(function() {
            klevu.support.hook(["recs"], function() {
                {$scriptString}
            });
        });

script
    : $scriptString;
?>
<?= $secureRenderer->renderTag(
    'script',
    [
        'type' => 'text/javascript',
        'id' => 'klevu_jsmodules',
    ],
    $priceSuffixString . PHP_EOL . $script,
    false
) ?>
