<?php
/**
 * @var Klevu\FrontendJs\Block\Html\Head\JsPreConnect $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php foreach ($block->getPreConnectUrls() as $preConnectUrl): ?>
    <?= $secureRenderer->renderTag(
        'link',
        [
            'rel' => 'preconnect',
            'href' => $block->escapeUrl($preConnectUrl),
            'crossorigin' => 'anonymous',
        ]
    ) ?>
<?php endforeach; ?>
